### ISSUE TITLE
1.12.2 version6 can not put potioncraft`s mix potion on armor

### ISSUE THREAD

**Issue by SIZStan** [Cookiehook/Minecraft-Liquid-Enchanting#30]
Just like the title...When mix three potion and copy them to 8, then put them all in crafttable with a iron armor. It seems like...the potion effect was disappear.
Like the picture
And, the potioncraft version is 1.1.1
![image](https://user-images.githubusercontent.com/37479377/80603018-72763900-8a62-11ea-8d53-18b97f8790c0.png)
![image](https://user-images.githubusercontent.com/37479377/80603049-7ace7400-8a62-11ea-8f0b-d258f2a0b04b.png)

**Comment by Cookiehook** [comment]
That's configurable, and disabled by default as I thought it OP.
Have you changed the config file to enable them? This is the option you need to set:
`B:"Enable Combined Crafting"=true`

**Comment by SIZStan** [comment]
AHA, thanks for reply~ Now, I know what going to do.
